controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - palm_finger_1_joint
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - palm_finger_2_joint
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_2_joint_3
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home